### ISSUE TITLE
Suggestion: Add warning if removing in-use Thing or Adapter

### ISSUE THREAD

**Issue by madb1lly** [WebThingsIO/gateway#2814] opened 2021-04-09 08:20 UTC
Hi WebThings team,

A useful improvement occurred to me today - for the Gateway UI to raise a warning if someone tries to remove a Thing or an Adapter which is currently in use. The reason for this is because Things can be used in rules and if they are removed the rules stop working. This is self-evident, however when we've got a lot of Things added we might forget which are used in rules and which are just providing information on the dashboard.

Cheers 🙂

**Comment by benfrancis** [comment] 2021-04-09 11:52
This is a good idea, but is also a duplicate of #735

**Closed by benfrancis** 2021-04-09 11:52 UTC

**Comment by madb1lly** [comment] 2021-04-09 12:16
Hi @benfrancis,
Drat, I should have checked first, please excuse me.
Cheers 🙂
