### ISSUE TITLE
Snapshot and video overlay remain when back button is pressed

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2793] opened 2021-02-23 15:11 UTC
The HTML back button is disabled when the video or snapshot overlay is present. But the real browser back button still works. This lead to a situation that confused me for a second.

- View a VideoCamera thing's livestream in the UI
- Press the back button in the browser

My instinctive expectation was that pressing the back button would close the overlay, bringing me back the thing overview. Instead, the overlay remained. When I closed that using the `(x)`, I was in the thing overview.

This is not a 'bug', just a user experience I wanted to share.

**Comment by benfrancis** [comment] 2021-02-24 13:02
Thanks for reporting this, I could have sworn this had already been fixed.

**Comment by benfrancis** [comment] 2021-02-24 13:03
Ah, I knew I'd seen this before. Duplicate of https://github.com/WebThingsIO/gateway/issues/1660

**Closed by benfrancis** 2021-02-24 13:03 UTC
Labels: bug
