### ISSUE TITLE
local ssl certificate

### ISSUE THREAD

**Issue by arist0v** [WebThingsIO/gateway#2931] opened 2022-05-09 19:53 UTC
could it be possible, to have an option to enable https on local side(with gateway.local in example) using vhttps: https://www.npmjs.com/package/vhttps

so we could , if we wish to, enable https with a self signed certs, or local CA certificate?

**Comment by benfrancis** [comment] 2022-05-10 11:19
We used to use self-signed certificates for the .local domain, but stopped using them because of the scary looking warnings they generate in web browsers. As I understand it, acting as a local certificate authority would require installing a root certificate on every device which is used to access the web interface via that domain. That's not user friendly enough to be the default, but could be offered as an optional feature for people who want it.

Closing as a duplicate of #171, but if you think this npm package brings a new solution to that discussion then please follow up in that issue. I bet the [HTTPS in Local Network Community Group](https://www.w3.org/community/httpslocal/) would like to hear about potential solutions too if there are new ideas.

**Closed by benfrancis** 2022-05-10 11:19 UTC
