### ISSUE TITLE
Webthings 1.1.0 Docker image new install failing to start

### ISSUE THREAD

**Issue by kcusoundman** [WebThingsIO/gateway#3066] opened 2023-01-20 21:52 UTC
Having had problems with the 1.1.0 docker image on a clean install not starting so did a bit of digging and worked out that putting a text file in the /home/node/.webthings folder named .node_version and ensure it's content is 12 will result in the image starting properly. If the file is missing the image will not start.

**Comment by benfrancis** [comment] 2023-02-13 11:25
Duplicate of #3043.

**Closed by benfrancis** 2023-02-13 11:25 UTC
Labels: duplicate
